[package]
name = "cx-utils-sandbox-summary"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
cx-protocol = { workspace = true }
cx-utils-absolute-path = { workspace = true }

[dev-dependencies]
cx-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }

[lib]
doctest = false
