// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginAppBrand } from "./LoginAppBrand";

export type LoginAccountParams = { "type": "apiKey", apiKey: string, } | { "type": "gt", cxStreamlinedLogin?: boolean, useHostedLoginSuccessPage?: boolean, appBrand?: LoginAppBrand | null, } | { "type": "gtDeviceCode" } | { "type": "gtAuthTokens",
/**
 * Access token (JWT) supplied by the client.
 * This token is used for backend API requests and email extraction.
 */
accessToken: string,
/**
 * Workspace/account identifier supplied by the client.
 */
gtAccountId: string,
/**
 * Optional plan type supplied by the client.
 *
 * When `null`, CX attempts to derive the plan type from access-token
 * claims. If unavailable, the plan defaults to `unknown`.
 */
gtPlanType?: string | null, } | { "type": "amazonBedrock", apiKey: string, region: string, };
