// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginAccountResponse = { "type": "apiKey", } | { "type": "gt", loginId: string,
/**
 * URL the client should open in a browser to initiate the OAuth flow.
 */
authUrl: string, } | { "type": "gtDeviceCode", loginId: string,
/**
 * URL the client should open in a browser to complete device code authorization.
 */
verificationUrl: string,
/**
 * One-time code the user must enter after signing in.
 */
userCode: string, } | { "type": "gtAuthTokens", } | { "type": "amazonBedrock", };
