[package]
edition.workspace = true
license.workspace = true
name = "cx-git-attribution"
version.workspace = true

[lib]
name = "cx_git_attribution"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
cx-backend-client = { workspace = true }
cx-extension-api = { workspace = true }
cx-http-client = { workspace = true }
cx-login = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = { workspace = true }
