[package]
edition.workspace = true
license.workspace = true
name = "cx-plugin"
version.workspace = true

[lib]
doctest = false
name = "cx_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
cx-config = { workspace = true }
cx-protocol = { workspace = true }
cx-utils-absolute-path = { workspace = true }
cx-utils-path-uri = { workspace = true }
cx-utils-plugins = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
